FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# Copy the rest of the application
COPY . .

# Expose the port (default: 3000)
EXPOSE 3000

# Start the application
 CMD ["node", "server.js"]
